apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

resources:
  - prometheus-deploy.yml
  - prometheus-service.yml
  - grafana-deploy.yml
  - grafana-service.yml
  - grafana-datasource.yml # optional, auto-config Prometheus as datasource
