apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: flask-namespace
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      # Scrape Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Scrape Node Exporter
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.flask-namespace.svc.cluster.local:9100']

      # Scrape Kube-State-Metrics
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.flask-namespace.svc.cluster.local:8080']

      # Scrape pods with prometheus annotations
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # Only scrape if annotation prometheus.io/scrape: "true"
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: "true"

          # Use custom metrics path if specified
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)

          # Use custom port if specified
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: (.+)
            target_label: __address__
            replacement: $1
