apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: flask-namespace
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: "flask-app"
        metrics_path: /metrics
        static_configs:
          - targets: ["flask-app-service.flask-namespace.svc.cluster.local:8080"]
      - job_name: "mysql"
        static_configs:
          - targets: ["mysql-service.flask-namespace.svc.cluster.local:3306"]
