apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: flask-namespace
spec:
  selector:
    app: flask-app-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
