apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: flask-namespace
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app-container
          image: shoeb5401/flask-mysql:v1
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: MYSQL_HOST
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: MYSQL_DB
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: MYSQL_PASSWORD

          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
