apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv

spec:
  storageClassName: ""
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mysql
    type: DirectoryOrCreate
